parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
  retrobon\MetaTagsBundle\Twig\MetaTagsTwigExtension: ~
  retrobon\MetaTagsBundle\Service\:
    resource: '../src/Service/'


